export type TherapyCategory =
  | "ABA"
  | "BCBA"
  | "Speech"
  | "OT"
  | "Psychology"
  | "Physiotherapy"
  | "Social Work"
  | "Recreation"
  | "Other";

export interface StatementSummary {
  provider: string;
  childName: string;
  accountName: string;
  accountNumber: string;

  statementDate: string;

  totalInvoiced: number;
  totalPaid: number;
  balance: number;
}

export interface TherapySession {
  /**
   * Unique identifier for this imported session.
   * Multiple sessions can belong to the same invoice,
   * so this must NOT be the invoice number.
   */
  id: string;

  invoiceNumber: string;

  invoiceDate: string;

  serviceDate: string;

  provider: string;

  therapist: string;

  /**
   * Description exactly as it appears on the invoice.
   *
   * NOTE:
   * We are keeping the property name "service" for now to
   * avoid a large refactor. Once Import Engine V2 is complete
   * we'll rename this to "description".
   */
  service: string;

  category: TherapyCategory;

  amount: number;

  imported?: boolean;
}

/**
 * Used only during the import workflow.
 * These values never get persisted to Firestore.
 */
export interface ImportableTherapySession
  extends TherapySession {
  /**
   * Whether this row will be imported.
   */
  selected: boolean;

  /**
   * Confidence score generated by Import Engine V2.
   */
  confidence: number;

  /**
   * Original text extracted from the PDF.
   * Useful for debugging and allowing users
   * to understand why a row was detected.
   */
  rawText: string;
}

export interface ParsedInvoice {
  summary: StatementSummary;

  sessions: ImportableTherapySession[];

  confidence: number;

  rawText: string;
}

export interface InvoiceParseResult {
  success: boolean;

  invoice?: ParsedInvoice;

  errors: string[];
}